name:                vulkan-playground
version:             0.1.0.0
github:              "1inguini/vulkan-playground"
license:             BSD3
author:              "1inguini"
maintainer:          "9647142@gmail.com"
copyright:           "2021 1inguini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/1inguini/vulkan-playground#readme>

dependencies:
- base >= 4.7 && < 5
- resourcet
# - managed
# - mtl
- safe-exceptions
# - unliftio-core
- text
- bytestring
- vector
- sdl2
- vulkan
- vulkan-utils

library:
  source-dirs: src

executables:
  vulkan-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vulkan-playground

tests:
  vulkan-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vulkan-playground

default-extensions:
- DataKinds
# - DefaultSignatures
# - DeriveFoldable
# - DeriveFunctor
# - DeriveTraversable
# - DerivingStrategies
- DuplicateRecordFields
# - FlexibleContexts
# - FlexibleInstances
# - GADTs
# - GeneralizedNewtypeDeriving
# - InstanceSigs
# - LambdaCase
# - MagicHash
# - NamedFieldPuns
# - NoMonomorphismRestriction
# - NumDecimals
- OverloadedStrings
- PatternSynonyms
# - PolyKinds
# - QuantifiedConstraints
- RankNTypes
# - RecordWildCards
# - RoleAnnotations
- ScopedTypeVariables
# - StandaloneDeriving
# - Strict
# - TupleSections
- TypeApplications
# - TypeFamilyDependencies
# - TypeOperators
# - TypeSynonymInstances
# - ViewPatterns

